### ISSUE TITLE
setting the server up using the vagrant way fails

### ISSUE THREAD

**Issue by kaosbeat** [roundware/roundware-server#402]
Hi,

I tried setting up my own round-ware server instance for a project as per instructions in the github README.
The vagrant up command fails (output below)

I'm having a feeling it has got to do with python2/3 issues.
when logging in this is what I get

```
roundware-server kaos$ vagrant ssh
Welcome to Ubuntu 14.04.6 LTS (GNU/Linux 3.13.0-170-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Wed Jul  1 10:00:52 UTC 2020

  System load:  0.0               Processes:           84
  Usage of /:   5.7% of 39.34GB   Users logged in:     0
  Memory usage: 11%               IP address for eth0: 10.0.2.15
  Swap usage:   0%

  Graph this data and manage this system at:
    https://landscape.canonical.com/

UA Infrastructure Extended Security Maintenance (ESM) is not enabled.

1 update can be installed immediately.
0 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Enable UA Infrastructure ESM to receive 151 additional security updates.
See https://ubuntu.com/advantage or run: sudo ua status


Last login: Wed Jul  1 10:00:53 2020 from 10.0.2.2
-bash: /var/www/roundware/bin/activate: No such file or directory
vagrant@roundware-server:~$ ls
```

further logging from the vagrant up command below

```
default: Cleaning up...
    default: # Create the virtual environment
    default: virtualenv --system-site-packages $VENV_PATH
    default: Traceback (most recent call last):
    default:   File "/usr/local/bin/virtualenv", line 7, in <module>
    default:     
    default: from virtualenv.__main__ import run_with_catch
    default:   File "/usr/local/lib/python2.7/dist-packages/virtualenv/__init__.py", line 3, in <module>
    default:     
    default: from .run import cli_run
    default:   File "/usr/local/lib/python2.7/dist-packages/virtualenv/run/__init__.py", line 11, in <module>
    default:     
    default: from .plugin.activators import ActivationSelector
    default:   File "/usr/local/lib/python2.7/dist-packages/virtualenv/run/plugin/activators.py", line 6, in <module>
    default:     
    default: from .base import ComponentBuilder
    default:   File "/usr/local/lib/python2.7/dist-packages/virtualenv/run/plugin/base.py", line 9, in <module>
    default:     
    default: from importlib_metadata import entry_points
    default:   File "/usr/local/lib/python2.7/dist-packages/importlib_metadata/__init__.py", line 9, in <module>
    default:     
    default: import zipp
    default: ImportError
    default: : 
    default: No module named zipp
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

```
